% Simscape(TM) Multibody(TM) version: 7.3

% This is a model data file derived from a Simscape Multibody Import XML file using the smimport function.
% The data in this file sets the block parameter values in an imported Simscape Multibody model.
% For more information on this file, see the smimport function help page in the Simscape Multibody documentation.
% You can modify numerical values, but avoid any other changes to this file.
% Do not add code to this file. Do not edit the physical units shown in comments.

%%%VariableName:smiData


%============= RigidTransform =============%

%Initialize the RigidTransform structure array by filling in null values.
% -------------------------------------------------------------------
%  Generated by MATLAB on 27-Mar-2022 10:14:04
%  MATLAB version: 9.12.0.1884302 (R2022a)
% -------------------------------------------------------------------
                                                          

smiData = struct;
smiData.RigidTransform = struct;
smiData.RigidTransform(1).translation = ...
  [2979.9999999999604 -107.99999999999876 3349.9999999999545];
smiData.RigidTransform(1).angle = 2.0943951023931953;
smiData.RigidTransform(1).axis = [-0.57735026918962562 -0.57735026918962584 ...
                                  -0.577350269189626];
smiData.RigidTransform(1).ID = 'B[T501_C-1:-:T501_A-1]';
smiData.RigidTransform(2).translation = ...
  [2979.9999999999623 -108.00000000000045 3349.9999999999568];
smiData.RigidTransform(2).angle = 2.0943951023931953;
smiData.RigidTransform(2).axis = [-0.57735026918962584 -0.57735026918962618 ...
                                  -0.5773502691896254];
smiData.RigidTransform(2).ID = 'F[T501_C-1:-:T501_A-1]';
smiData.RigidTransform(3).translation = ...
  [2600 -2.5229280231553817E-13 3350.0000000000009];
smiData.RigidTransform(3).angle = 2.0943951023931953;
smiData.RigidTransform(3).axis = [0.577350269189626 0.57735026918962584 ...
                                  0.57735026918962562];
smiData.RigidTransform(3).ID = 'B[T403-1:-:T501_A-1]';
smiData.RigidTransform(4).translation = ...
  [2599.9999999999636 -4.5474735088646412E-13 3349.9999999999554];
smiData.RigidTransform(4).angle = 2.0943951023931957;
smiData.RigidTransform(4).axis = [0.57735026918962562 0.57735026918962573 ...
                                  0.57735026918962573];
smiData.RigidTransform(4).ID = 'F[T403-1:-:T501_A-1]';
smiData.RigidTransform(5).translation = ...
  [2979.9999999999595 109.99999999999987 3349.999999999955];
smiData.RigidTransform(5).angle = 2.0943951023931957;
smiData.RigidTransform(5).axis = [0.57735026918962584 -0.57735026918962573 ...
                                  0.57735026918962573];
smiData.RigidTransform(5).ID = 'B[T501_A-6:-:T501_C-6]';
smiData.RigidTransform(6).translation = ...
  [2979.9999999999536 110.00000000000091 3349.9999999999509];
smiData.RigidTransform(6).angle = 2.0943951023931962;
smiData.RigidTransform(6).axis = [0.577350269189626 -0.577350269189626 ...
                                  0.57735026918962529];
smiData.RigidTransform(6).ID = 'F[T501_A-6:-:T501_C-6]';
smiData.RigidTransform(7).translation = ...
  [3424.9999999999591 0 3349.9999999999504];
smiData.RigidTransform(7).angle = 2.0943951023931953;
smiData.RigidTransform(7).axis = [-0.57735026918962562 -0.57735026918962584 ...
                                  0.577350269189626];
smiData.RigidTransform(7).ID = 'B[T501_D-1:-:T501_A-6]';
smiData.RigidTransform(8).translation = ...
  [2589.9999999999613 -4.5474735088646412E-13 3349.9999999999554];
smiData.RigidTransform(8).angle = 2.0943951023931957;
smiData.RigidTransform(8).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                  0.57735026918962562];
smiData.RigidTransform(8).ID = 'F[T501_D-1:-:T501_A-6]';
smiData.RigidTransform(9).translation = ...
  [3394.4999999999604 0 3349.9999999999504];
smiData.RigidTransform(9).angle = 2.0943951023931953;
smiData.RigidTransform(9).axis = [-0.57735026918962562 -0.57735026918962584 ...
                                  0.577350269189626];
smiData.RigidTransform(9).ID = 'B[T501_D-1:-:T501_C-1]';
smiData.RigidTransform(10).translation = ...
  [3394.500000000005 1.8189894035458565E-12 3350.0000000000018];
smiData.RigidTransform(10).angle = 2.0943951023931957;
smiData.RigidTransform(10).axis = [-0.577350269189626 -0.57735026918962573 ...
                                   0.57735026918962551];
smiData.RigidTransform(10).ID = 'F[T501_D-1:-:T501_C-1]';
smiData.RigidTransform(11).translation = ...
  [3394.5 4.4408920985006262E-13 3349.9999999999995];
smiData.RigidTransform(11).angle = 2.0943951023931953;
smiData.RigidTransform(11).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                   0.57735026918962584];
smiData.RigidTransform(11).ID = 'B[T501_C-6:-:T501_D-6]';
smiData.RigidTransform(12).translation = ...
  [3394.4999999999618 1.8189894035458565E-12 3349.9999999999509];
smiData.RigidTransform(12).angle = 2.0943951023931953;
smiData.RigidTransform(12).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                   0.57735026918962584];
smiData.RigidTransform(12).ID = 'F[T501_C-6:-:T501_D-6]';
smiData.RigidTransform(13).translation = ...
  [3424.9999999999591 0 3349.99999999995];
smiData.RigidTransform(13).angle = 2.0943951023931953;
smiData.RigidTransform(13).axis = [-0.57735026918962551 -0.57735026918962562 ...
                                   0.57735026918962606];
smiData.RigidTransform(13).ID = 'B[T501_D-6:-:Cabina-2]';
smiData.RigidTransform(14).translation = ...
  [-0.33388185262759862 353.93770478588777 649.54340112144109];
smiData.RigidTransform(14).angle = 6.4736570491389385E-16;
smiData.RigidTransform(14).axis = [0.42658568639798383 -0.90444715277364929 ...
                                   -1.2488468067034847E-16];
smiData.RigidTransform(14).ID = 'F[T501_D-6:-:Cabina-2]';
smiData.RigidTransform(15).translation = ...
  [500 422 3000.0000000000005];
smiData.RigidTransform(15).angle = 2.0943951023931953;
smiData.RigidTransform(15).axis = [0.57735026918962584 -0.57735026918962584 ...
                                   0.57735026918962584];
smiData.RigidTransform(15).ID = 'B[T403-1:-:T301_B-1]';
smiData.RigidTransform(16).translation = ...
  [499.99999999999426 421.99999999999972 3000.0000000000596];
smiData.RigidTransform(16).angle = 2.0943951023931957;
smiData.RigidTransform(16).axis = [0.57735026918962584 -0.57735026918962551 ...
                                   0.577350269189626];
smiData.RigidTransform(16).ID = 'F[T403-1:-:T301_B-1]';
smiData.RigidTransform(17).translation = ...
  [-300.00000000003058 63.999999999996561 3000];
smiData.RigidTransform(17).angle = 2.0943951023931953;
smiData.RigidTransform(17).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                   -0.57735026918962584];
smiData.RigidTransform(17).ID = 'B[T301_D-1:-:T403-1]';
smiData.RigidTransform(18).translation = ...
  [-300.0000000008564 72.999999999996817 2999.9999999987285];
smiData.RigidTransform(18).angle = 2.0943951023931935;
smiData.RigidTransform(18).axis = [-0.57735026918962506 -0.57735026918962662 ...
                                   -0.57735026918962562];
smiData.RigidTransform(18).ID = 'F[T301_D-1:-:T403-1]';
smiData.RigidTransform(19).translation = ...
  [1.5820678100908503E-12 -4.0435175101681019E-13 306.99999999999989];
smiData.RigidTransform(19).angle = 3.1415926535897918;
smiData.RigidTransform(19).axis = [-1 -1.1950430378579322E-30 2.1515705802505583E-15 ...
                                   ];
smiData.RigidTransform(19).ID = 'B[T301_A-1:-:T201_A-1]';
smiData.RigidTransform(20).translation = ...
  [-1.5807577559295224E-13 -2.4112420927689856E-13 309.99999999999994];
smiData.RigidTransform(20).angle = 3.1415926535897931;
smiData.RigidTransform(20).axis = [-1 2.440744789650781E-35 -6.4031684558611869E-17 ...
                                   ];
smiData.RigidTransform(20).ID = 'F[T301_A-1:-:T201_A-1]';
smiData.RigidTransform(21).translation = ...
  [500.00000000000045 443.00000000001415 1300.0000000000005];
smiData.RigidTransform(21).angle = 2.0943951023931953;
smiData.RigidTransform(21).axis = [0.57735026918962584 -0.57735026918962584 ...
                                   0.57735026918962584];
smiData.RigidTransform(21).ID = 'B[T303_C-1:-:T301_A-1]';
smiData.RigidTransform(22).translation = ...
  [499.999999999499 443.00000000000114 1300.0000000002747];
smiData.RigidTransform(22).angle = 2.0943951023931975;
smiData.RigidTransform(22).axis = [0.57735026918962651 -0.5773502691896264 ...
                                   0.57735026918962429];
smiData.RigidTransform(22).ID = 'F[T303_C-1:-:T301_A-1]';
smiData.RigidTransform(23).translation = ...
  [297.96608653102254 -270.99999999999994 1226.4656691849802];
smiData.RigidTransform(23).angle = 2.0943951023931953;
smiData.RigidTransform(23).axis = [-0.57735026918962584 -0.5773502691896254 ...
                                   -0.57735026918962618];
smiData.RigidTransform(23).ID = 'B[T301_E-1:-:T301_B-1]';
smiData.RigidTransform(24).translation = ...
  [297.9660865305093 -259.50000000000426 1226.4656691853193];
smiData.RigidTransform(24).angle = 2.0943951023931953;
smiData.RigidTransform(24).axis = [-0.57735026918962584 -0.577350269189626 ...
                                   -0.57735026918962551];
smiData.RigidTransform(24).ID = 'F[T301_E-1:-:T301_B-1]';
smiData.RigidTransform(25).translation = ...
  [500.00000000000045 256.00000000000006 1300.0000000000002];
smiData.RigidTransform(25).angle = 2.0943951023931939;
smiData.RigidTransform(25).axis = [0.57735026918962518 -0.57735026918962551 ...
                                   0.57735026918962662];
smiData.RigidTransform(25).ID = 'B[T303_C-1:-:T301_B-1]';
smiData.RigidTransform(26).translation = ...
  [499.99999999961869 255.99999999998539 1300.0000000004247];
smiData.RigidTransform(26).angle = 2.0943951023931979;
smiData.RigidTransform(26).axis = [0.57735026918962651 -0.57735026918962629 ...
                                   0.57735026918962451];
smiData.RigidTransform(26).ID = 'F[T303_C-1:-:T301_B-1]';
smiData.RigidTransform(27).translation = ...
  [-300.00000000003058 63.999999999996618 1299.9999999999436];
smiData.RigidTransform(27).angle = 2.0943951023931953;
smiData.RigidTransform(27).axis = [-0.57735026918962584 -0.57735026918962584 ...
                                   -0.57735026918962584];
smiData.RigidTransform(27).ID = 'B[T301_D-1:-:T303_C-1]';
smiData.RigidTransform(28).translation = ...
  [-300.00000000003831 73.000000000016485 1299.9999999994511];
smiData.RigidTransform(28).angle = 2.0943951023931984;
smiData.RigidTransform(28).axis = [-0.57735026918962684 -0.57735026918962618 ...
                                   -0.5773502691896244];
smiData.RigidTransform(28).ID = 'F[T301_D-1:-:T303_C-1]';
smiData.RigidTransform(29).translation = ...
  [-743.54760345913792 -230.99999999999997 1361.310009444592];
smiData.RigidTransform(29).angle = 2.1702590554786321;
smiData.RigidTransform(29).axis = [0.6005790033793742 0.60057900337937353 ...
                                   0.5278349376459236];
smiData.RigidTransform(29).ID = 'B[T301_F-1:-:T301_E-1]';
smiData.RigidTransform(30).translation = ...
  [-480.53625632854579 -230.99999999999977 1327.2580407326391];
smiData.RigidTransform(30).angle = 2.1702590554786321;
smiData.RigidTransform(30).axis = [0.60057900337937387 0.60057900337937375 ...
                                   0.52783493764592371];
smiData.RigidTransform(30).ID = 'F[T301_F-1:-:T301_E-1]';
smiData.RigidTransform(31).translation = ...
  [0 0 0];
smiData.RigidTransform(31).angle = 0;
smiData.RigidTransform(31).axis = [0 0 0];
smiData.RigidTransform(31).ID = 'RootGround[T201_A-1]';
smiData.Solid = struct;
smiData.Solid(1).mass = 321.69005434036018;
smiData.Solid(1).CoM = [1026.9462240281096 52.210572517887933 3237.840968234379 ...
                        ];
smiData.Solid(1).MoI = [2.0827547392620437E+7 2.1838631741253239E+8 2.1529937597345656E+8 ...
                        ];
smiData.Solid(1).PoI = [3.1960319145785114E+6 -2.5978038800147194E+7 1.337239034619211E+7 ...
                        ];
smiData.Solid(1).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(1).opacity = 1;
smiData.Solid(1).ID = 'T403*:*Predeterminado';
smiData.Solid(2).mass = 6210.742539956881;
smiData.Solid(2).CoM = [0.011123052221127765 -11.797941888356695 3.6818695155398533 ...
                        ];
smiData.Solid(2).MoI = [1.0183074856986517E+8 9.5690566596206322E+7 1.0370426287306927E+8 ...
                        ];
smiData.Solid(2).PoI = [2.1879410076428913E+6 -20438.074885783644 -40917.6412336627 ...
                        ];
smiData.Solid(2).color = [0.58196078431372544 0.55999999999999994 0.52980392156862743 ...
                          ];
smiData.Solid(2).opacity = 1;
smiData.Solid(2).ID = 'Cabina*:*Predeterminado';
smiData.Solid(3).mass = 23.517344270570852;
smiData.Solid(3).CoM = [2822.4075991462978 -12.863717936717004 3350.0000150170158 ...
                        ];
smiData.Solid(3).MoI = [259489.55217921743 714780.6817692999 708024.78286019654 ...
                        ];
smiData.Solid(3).PoI = [-0.40401466553187132 0.046890787205918508 53177.53272907935 ...
                        ];
smiData.Solid(3).color = [0.8 0.8 0.8];
smiData.Solid(3).opacity = 1;
smiData.Solid(3).ID = 'T501_A*:*Predeterminado';
smiData.Solid(4).mass = 57.944443118224036;
smiData.Solid(4).CoM = [3108.6026250002742 -59.078193491949165 3350.0000062825534 ...
                        ];
smiData.Solid(4).MoI = [1.9168182496621558E+6 2.159741827228683E+6 3.0054647491910798E+6 ...
                        ];
smiData.Solid(4).PoI = [-0.0859123125278659 -0.051117654376571148 -523262.15749401751 ...
                        ];
smiData.Solid(4).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(4).opacity = 1;
smiData.Solid(4).ID = 'T501_C*:*Predeterminado';
smiData.Solid(5).mass = 4.0575817185089109;
smiData.Solid(5).CoM = [3405.4585434016976 0 3349.99999999995];
smiData.Solid(5).MoI = [90358.412057542329 45749.378697781729 45749.378697781714 ...
                        ];
smiData.Solid(5).PoI = [0 0 0];
smiData.Solid(5).color = [0.8 0.8 0.8];
smiData.Solid(5).opacity = 1;
smiData.Solid(5).ID = 'T501_D*:*Predeterminado';
smiData.Solid(6).mass = 144.32732731541017;
smiData.Solid(6).CoM = [-466.40163850963194 -231.00000027577263 1325.2183970164383 ...
                        ];
smiData.Solid(6).MoI = [4.0030338286168678E+6 1.1416991273749813E+7 1.1408232293758756E+7 ...
                        ];
smiData.Solid(6).PoI = [-0.27832837126040422 973289.19554778282 -0.055453484183058621 ...
                        ];
smiData.Solid(6).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(6).opacity = 1;
smiData.Solid(6).ID = 'T301_F*:*Predeterminado';
smiData.Solid(7).mass = 4.0753058345407913;
smiData.Solid(7).CoM = [-3.8205190077372313 -230.99999999999991 1265.5378543268241 ...
                        ];
smiData.Solid(7).MoI = [9872.60328384781 255566.07391019276 248920.09925417084 ...
                        ];
smiData.Solid(7).PoI = [0 31477.008290205271 0];
smiData.Solid(7).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(7).opacity = 1;
smiData.Solid(7).ID = 'T301_E*:*Predeterminado';
smiData.Solid(8).mass = 441.14233063575728;
smiData.Solid(8).CoM = [285.2511358616967 -8.5373279625193987 905.399820146292 ...
                        ];
smiData.Solid(8).MoI = [1.8103876967723572E+8 1.2212753908417223E+8 1.50181241455013E+8 ...
                        ];
smiData.Solid(8).PoI = [1.4395054762851631E+6 -3.2179044700461768E+7 -3.3309879325991469E+6 ...
                        ];
smiData.Solid(8).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(8).opacity = 1;
smiData.Solid(8).ID = 'T301_A*:*Predeterminado';
smiData.Solid(9).mass = 268.9049536163497;
smiData.Solid(9).CoM = [-661.37067869113946 130.42767814346331 1451.9892527193724 ...
                        ];
smiData.Solid(9).MoI = [3.7036149688382573E+7 1.2482606227617691E+8 1.4378265928491369E+8 ...
                        ];
smiData.Solid(9).PoI = [7.2982631118491367E+6 2.0587500179816719E+7 -3.45782902287163E+7 ...
                        ];
smiData.Solid(9).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(9).opacity = 1;
smiData.Solid(9).ID = 'T303_C*:*Predeterminado';
smiData.Solid(10).mass = 355.37700809974979;
smiData.Solid(10).CoM = [-65.8232784988106 0.036773684719146583 146.05573315748629 ...
                         ];
smiData.Solid(10).MoI = [3.2286884880914513E+7 4.44689054663843E+7 7.14525741123794E+7 ...
                         ];
smiData.Solid(10).PoI = [1582.0196081611034 -26825.847672129319 -860.212961682309 ...
                         ];
smiData.Solid(10).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                           ];
smiData.Solid(10).opacity = 1;
smiData.Solid(10).ID = 'T201_A*:*Predeterminado';
smiData.Solid(11).mass = 37.11699979503949;
smiData.Solid(11).CoM = [-473.32554820908723 370.00000000000006 2149.9999999999695 ...
                         ];
smiData.Solid(11).MoI = [9.2010289134625327E+6 9.6498603589749224E+6 492785.68638626568 ...
                         ];
smiData.Solid(11).PoI = [0 -3.5870433431440777E-8 0];
smiData.Solid(11).color = [0.8 0.8 0.8];
smiData.Solid(11).opacity = 1;
smiData.Solid(11).ID = 'T301_D*:*Predeterminado';
smiData.Solid(12).mass = 706.95319763939835;
smiData.Solid(12).CoM = [664.23974712148663 46.21956204958672 2077.8759850243318 ...
                         ];
smiData.Solid(12).MoI = [2.4820297190845853E+8 2.073787343949008E+8 8.3380393474183664E+7 ...
                         ];
smiData.Solid(12).PoI = [-4.8567309920912683E+7 -4.0489532057273453E+6 ...
                         -3.0382517348325644E+6];
smiData.Solid(12).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                           ];
smiData.Solid(12).opacity = 1;
smiData.Solid(12).ID = 'T301_B*:*Predeterminado';
smiData.RevoluteJoint = struct;
smiData.RevoluteJoint(1).Rz = struct;
smiData.RevoluteJoint(1).Rz.Pos = -1.5293524487891366;
smiData.RevoluteJoint(1).ID = '[T501_C-1:-:T501_A-1]';
smiData.RevoluteJoint(2).Rz = struct;
smiData.RevoluteJoint(2).Rz.Pos = 64.164119997833765;
smiData.RevoluteJoint(2).ID = '[T403-1:-:T501_A-1]';
smiData.RevoluteJoint(3).Rz = struct;
smiData.RevoluteJoint(3).Rz.Pos = 30.933990396451698;
smiData.RevoluteJoint(3).ID = '[T501_A-6:-:T501_C-6]';
smiData.RevoluteJoint(4).Rz = struct;
smiData.RevoluteJoint(4).Rz.Pos = 92.400795320308177;
smiData.RevoluteJoint(4).ID = '[T501_D-1:-:T501_A-6]';
smiData.RevoluteJoint(5).Rz = struct;
smiData.RevoluteJoint(5).Rz.Pos = -71.859502438446142;
smiData.RevoluteJoint(5).ID = '[T501_D-1:-:T501_C-1]';
smiData.RevoluteJoint(6).Rz = struct;
smiData.RevoluteJoint(6).Rz.Pos = 41.690060020059228;
smiData.RevoluteJoint(6).ID = '[T501_C-6:-:T501_D-6]';
smiData.RevoluteJoint(7).Rz = struct;
smiData.RevoluteJoint(7).Rz.Pos = 11.425365988034939;
smiData.RevoluteJoint(7).ID = '[T501_D-6:-:Cabina-2]';
smiData.RevoluteJoint(8).Rz = struct;
smiData.RevoluteJoint(8).Rz.Pos = 51.745523946925871;
smiData.RevoluteJoint(8).ID = '[T403-1:-:T301_B-1]';
smiData.RevoluteJoint(9).Rz = struct;
smiData.RevoluteJoint(9).Rz.Pos = 51.745523946939748;
smiData.RevoluteJoint(9).ID = '[T301_D-1:-:T403-1]';
smiData.RevoluteJoint(10).Rz = struct;
smiData.RevoluteJoint(10).Rz.Pos = -102.60720223772684;
smiData.RevoluteJoint(10).ID = '[T301_A-1:-:T201_A-1]';
smiData.RevoluteJoint(11).Rz = struct;
smiData.RevoluteJoint(11).Rz.Pos = 32.271571124786284;
smiData.RevoluteJoint(11).ID = '[T303_C-1:-:T301_A-1]';
smiData.RevoluteJoint(12).Rz = struct;
smiData.RevoluteJoint(12).Rz.Pos = -6.2989825444387373;
smiData.RevoluteJoint(12).ID = '[T301_E-1:-:T301_B-1]';
smiData.RevoluteJoint(13).Rz = struct;
smiData.RevoluteJoint(13).Rz.Pos = 51.745523946899752;
smiData.RevoluteJoint(13).ID = '[T303_C-1:-:T301_B-1]';
smiData.RevoluteJoint(14).Rz = struct;
smiData.RevoluteJoint(14).Rz.Pos = 51.745523946913636;
smiData.RevoluteJoint(14).ID = '[T301_D-1:-:T303_C-1]';
smiData.RevoluteJoint(15).Rz = struct;
smiData.RevoluteJoint(15).Rz.Pos = 57.991926565867011;
smiData.RevoluteJoint(15).ID = '[T301_F-1:-:T301_E-1]';

